run_title: 'use_this'

training_model:
  kind: default
  visualize_each_iters: 1000
  concat_mask: true
  store_discr_outputs_for_vis: true
losses:
  l1:
    weight_missing: 0
    weight_known: 10
  perceptual:
    weight: 0
  adversarial:
    kind: r1
    weight: 10
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  feature_matching:
    weight: 100
  total_variational:
    weight: 20
  style:
    weight: 0
  structure:
    weight: 0
  gan_reconstruction:
    weight: 0
  contextual:
    weight: 10
  edges:
    weight: 10
  gradient_different:
    weight: 10
  HAD:
    weight: 10
  MSSSIM:
    weight: 10
  AA:
    weight: 10
  DFCP:
    weight: 10
  PP:
    weight: 10
  patchgan:
    weight: 10
  resnet_pl:
    weight: 30
    weights_path: ${env:TORCH_HOME}

defaults:
  - location: docker
  - data: abl-04-256-mh-dist
  - generator: ffc_resnet_075
  - discriminator: pix2pixhd_nlayer
  - optimizers: default_optimizers
  - visualizer: directory
  - evaluator: default_inpainted
  - trainer: any_gpu_large_ssim_ddp_final
  - hydra: overrides
